name: Setup SQLCMD and ODBC Driver

on: push


jobs:
  setup-sql-tools:
    runs-on: windows-latest # Your Windows self-hosted runner

    steps:
    - name: 🧰 Create temp folder
      run: |
        New-Item -Path "C:\temp" -ItemType Directory -Force

    - name: ✅ Download and install ODBC Driver 17
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2307162" -OutFile "C:\temp\msodbcsql.msi"
        Start-Process msiexec.exe -Wait -ArgumentList '/i C:\temp\msodbcsql.msi /quiet /norestart IACCEPTMSODBCSQLLICENSETERMS=YES'

    - name: ✅ Download and install classic SQLCMD
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2216599" -OutFile "C:\temp\SqlCmdLnUtils.msi"
        Start-Process msiexec.exe -Wait -ArgumentList '/i C:\temp\SqlCmdLnUtils.msi /quiet /norestart IACCEPTSQLCMDLNUTILSLICENSETERMS=YES'
    
    - name: 🔍 Locate sqlcmd.exe
      run: |
        Get-ChildItem -Path "C:\" -Recurse -Filter "sqlcmd.exe" -ErrorAction SilentlyContinue | Select-Object -First 5 FullName
    
